version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: service-nodejs-loan-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      target: ${NODE_ENV}
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: service-nodejs-loan-nestjs
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3000:${SERVER_PORT}"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./:/node/app:delegated
      - /node/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: service-nodejs-loan-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@loanservice.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
